[package]
name = "Tm_Os"
version = "0.1.0"
edition = "2018"

[dependencies]
bootloader = "0.9.33"
spin = "0.5.2"
x86_64 = "0.14"


[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
